using System.Text;

namespace TypedPrompt.Core;

/// <summary>
/// Generates one C# class per prompt: the values in the constructor (required variables are required parameters),
/// a property per value, a static <c>Definition</c>, and a <c>Render()</c> that concatenates the template pieces split
/// at build time. The code needs C# 9 or later and the TypedPrompt runtime package.
/// </summary>
public sealed class CSharpEmitter(CSharpEmitOptions options) : IPromptEmitter
{
    private const string Runtime = "global::TypedPrompt.";

    /// <inheritdoc />
    public string Language => "csharp";

    /// <inheritdoc />
    public EmitResult Emit(ParsedPrompt prompt)
    {
        var className = prompt.Name + options.ClassSuffix;
        var problems = NameConflicts.Find(prompt, className, CSharpSyntax.PropertyName, "C#");
        if (problems.Count > 0)
        {
            return new EmitResult([], problems);
        }

        var code = new CodeWriter();
        var file = System.IO.Path.GetFileName(prompt.Path);
        code.Line("// <auto-generated/>");
        code.Line($"// Generated by TypedPrompt from {file}. Do not edit: change the .prompt.toml file instead.");
        code.Line("#nullable enable");
        code.Line();
        code.Open($"namespace {options.Namespace}");
        code.Line($"/// <summary>{CSharpSyntax.Xml(prompt.Description ?? $"The prompt defined in {file}.")}</summary>");
        code.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"TypedPrompt\", {CSharpSyntax.Literal(options.GeneratorVersion)})]");
        code.Open($"public sealed partial class {className} : {Runtime}ITypedPrompt");

        WriteDefinition(code, prompt, file);
        WriteConstructor(code, prompt, className);
        WriteProperties(code, prompt);
        code.Line($"{Runtime}PromptDefinition {Runtime}ITypedPrompt.Definition => Definition;");
        code.Line();
        WriteRender(code, prompt);

        code.Close();
        code.Close();
        return new EmitResult([new EmittedFile(className + ".g.cs", code.ToString())], []);
    }

    private static void WriteDefinition(CodeWriter code, ParsedPrompt prompt, string file)
    {
        code.Line($"/// <summary>What {CSharpSyntax.Xml(file)} defines: key, templates, model settings, output schema, variables and metadata.</summary>");
        code.Line($"public static {Runtime}PromptDefinition Definition {{ get; }} = new {Runtime}PromptDefinition(");
        code.Indented($"{CSharpSyntax.Literal(prompt.Key)},");
        code.Indented($"{CSharpSyntax.Literal(prompt.User.Text)})");
        code.Open(string.Empty, trailing: "};");
        code.Line($"ContentHash = {CSharpSyntax.Literal(prompt.ContentHash)},");
        if (prompt.VersionLabel is { } label)
        {
            code.Line($"VersionLabel = {CSharpSyntax.Literal(label)},");
        }

        if (prompt.System is { } system)
        {
            code.Line($"SystemTemplate = {CSharpSyntax.Literal(system.Text)},");
        }

        if (prompt.Examples.Count > 0)
        {
            code.Line($"Examples = new {Runtime}PromptExample[]");
            code.Open(string.Empty, trailing: "},");
            foreach (var example in prompt.Examples)
            {
                code.Line($"new {Runtime}PromptExample({CSharpSyntax.Literal(example.User.Text)}, {CSharpSyntax.Literal(example.Assistant.Text)}),");
            }

            code.Close();
        }

        if (prompt.Description is { } description)
        {
            code.Line($"Description = {CSharpSyntax.Literal(description)},");
        }

        if (prompt.Tags.Count > 0)
        {
            code.Line($"Tags = new string[] {{ {string.Join(", ", prompt.Tags.Select(CSharpSyntax.Literal))} }},");
        }

        if (prompt.Metadata.Count > 0)
        {
            code.Line("Metadata = new global::System.Collections.Generic.Dictionary<string, string>");
            code.Open(string.Empty, trailing: "},");
            foreach (var pair in prompt.Metadata)
            {
                code.Line($"[{CSharpSyntax.Literal(pair.Key)}] = {CSharpSyntax.Literal(pair.Value)},");
            }

            code.Close();
        }

        if (prompt.Model is { } model)
        {
            var arguments = new List<string>();
            void Add(string name, string? value)
            {
                if (value is not null)
                {
                    arguments.Add($"{name}: {value}");
                }
            }

            Add("Name", model.Name is null ? null : CSharpSyntax.Literal(model.Name));
            Add("Temperature", model.Temperature is { } temperature ? CSharpSyntax.Literal(temperature) : null);
            Add("TopP", model.TopP is { } topP ? CSharpSyntax.Literal(topP) : null);
            Add("TopK", model.TopK?.ToString(System.Globalization.CultureInfo.InvariantCulture));
            Add("MaxOutputTokens", model.MaxOutputTokens?.ToString(System.Globalization.CultureInfo.InvariantCulture));
            Add("StopSequences", model.StopSequences is { } stops ? $"new string[] {{ {string.Join(", ", stops.Select(CSharpSyntax.Literal))} }}" : null);
            Add("Effort", model.Effort is null ? null : CSharpSyntax.Literal(model.Effort));
            code.Line($"Model = new {Runtime}ModelSettings({string.Join(", ", arguments)}),");
        }

        if (prompt.OutputSchema is { } schema)
        {
            code.Line($"OutputSchema = {CSharpSyntax.Literal(schema)},");
        }

        if (prompt.Variables.Count > 0)
        {
            code.Line($"Variables = new {Runtime}VariableInfo[]");
            code.Open(string.Empty, trailing: "},");
            foreach (var variable in prompt.Variables)
            {
                code.Line($"new {Runtime}VariableInfo({CSharpSyntax.Literal(variable.Name)}, {Runtime}VariableType.{variable.Kind}, "
                    + $"{CSharpSyntax.Literal(variable.Required)}, {CSharpSyntax.Literal(variable.Default)}, {CSharpSyntax.Literal(variable.Description)}),");
            }

            code.Close();
        }

        code.Close();
        code.Line();
    }

    private static void WriteConstructor(CodeWriter code, ParsedPrompt prompt, string className)
    {
        var ordered = Ordered(prompt);
        code.Line("/// <summary>Creates the prompt with its values; call <see cref=\"Render\"/> to fill the templates.</summary>");
        foreach (var variable in ordered)
        {
            code.Line($"/// <param name=\"{CSharpSyntax.ParameterName(variable.Name).TrimStart('@')}\">{CSharpSyntax.Xml(Describe(variable))}</param>");
        }

        var parameters = ordered.Select(v => $"{ParameterType(v)} {CSharpSyntax.ParameterName(v.Name)}{ParameterDefault(v)}");
        code.Open($"public {className}({string.Join(", ", parameters)})");
        foreach (var variable in ordered)
        {
            var parameter = CSharpSyntax.ParameterName(variable.Name);
            var value = IsNullable(variable) || variable.Kind != VariableKind.Text
                ? parameter
                : $"{parameter} ?? throw new global::System.ArgumentNullException(nameof({parameter}))";
            code.Line($"{CSharpSyntax.PropertyName(variable.Name)} = {value};");
        }

        code.Close();
        code.Line();
    }

    private static void WriteProperties(CodeWriter code, ParsedPrompt prompt)
    {
        foreach (var variable in prompt.Variables)
        {
            code.Line($"/// <summary>{CSharpSyntax.Xml(Describe(variable))}</summary>");
            code.Line($"public {ParameterType(variable)} {CSharpSyntax.PropertyName(variable.Name)} {{ get; }}");
            code.Line();
        }
    }

    private static void WriteRender(CodeWriter code, ParsedPrompt prompt)
    {
        code.Line("/// <summary>Fills every placeholder with this instance's values.</summary>");
        code.Open($"public {Runtime}RenderedPrompt Render()");
        code.Line($"return new {Runtime}RenderedPrompt(");
        code.Indented("Definition.Key,");
        code.Indented($"{(prompt.System is { } system ? Concat(system) : "null")},");
        code.Indented($"{Concat(prompt.User)},");
        code.Indented("Definition.Model,");
        code.Indented("Definition.OutputSchema)");
        code.Open(string.Empty, trailing: "};");
        code.Line("Version = Definition.Version,");
        if (prompt.Examples.Count > 0)
        {
            code.Line($"Examples = new {Runtime}PromptExample[]");
            code.Open(string.Empty, trailing: "},");
            foreach (var example in prompt.Examples)
            {
                code.Line($"new {Runtime}PromptExample({Concat(example.User)}, {Concat(example.Assistant)}),");
            }

            code.Close();
        }

        code.Close();
        code.Close();
    }

    /// <summary>The template pieces as one C# expression: literals and formatted property values.</summary>
    private static string Concat(Template template)
    {
        var parts = template.Segments
            .Select(s => s.Kind == TemplateSegmentKind.Text
                ? CSharpSyntax.Literal(s.Value)
                : $"{Runtime}PromptValue.Format({CSharpSyntax.PropertyName(s.Value)})")
            .ToList();

        return parts.Count switch
        {
            0 => "\"\"",
            1 => parts[0],
            _ => $"string.Concat(new string[] {{ {string.Join(", ", parts)} }})",
        };
    }

    /// <summary>Required parameters first (C# needs that), each group in file order.</summary>
    private static List<ParsedVariable> Ordered(ParsedPrompt prompt) =>
        prompt.Variables.Where(v => v.Required).Concat(prompt.Variables.Where(v => !v.Required)).ToList();

    /// <summary>Optional without a default: the parameter is nullable and defaults to null (renders as empty text).</summary>
    private static bool IsNullable(ParsedVariable variable) => !variable.Required && variable.Default is null;

    private static string ParameterType(ParsedVariable variable)
    {
        var type = variable.Kind switch
        {
            VariableKind.Number => "double",
            VariableKind.Boolean => "bool",
            _ => "string",
        };
        return IsNullable(variable) ? type + "?" : type;
    }

    private static string ParameterDefault(ParsedVariable variable) =>
        variable.Required ? string.Empty : $" = {CSharpSyntax.Literal(variable.Default)}";

    private static string Describe(ParsedVariable variable)
    {
        var text = new StringBuilder(variable.Description ?? $"Value of {{{{{variable.Name}}}}}.");
        if (text.Length > 0 && text[text.Length - 1] is not ('.' or '!' or '?'))
        {
            text.Append('.');
        }

        if (!variable.Required)
        {
            text.Append(variable.Default is null ? " Optional." : $" Default: {Display(variable.Default)}.");
        }

        return text.ToString();
    }

    private static string Display(object value) => value switch
    {
        double number => number.ToString("R", System.Globalization.CultureInfo.InvariantCulture),
        bool flag => flag ? "true" : "false",
        _ => value.ToString() ?? string.Empty,
    };
}
