using System.Globalization;
using System.Text;

namespace TypedPrompt.Core;

/// <summary>
/// Generates one F# class per prompt, in idiomatic F#: a primary constructor with required parameters first and
/// <c>?optional</c> ones after, a property per value (an optional variable without a default is an <c>option</c>), a
/// static <c>Definition</c>, <c>Render()</c>, and <c>ITypedPrompt</c>. Uses the same TypedPrompt runtime package as C#.
/// </summary>
public sealed class FSharpEmitter(FSharpEmitOptions options) : IPromptEmitter
{
    /// <inheritdoc />
    public string Language => "fsharp";

    /// <inheritdoc />
    public EmitResult Emit(ParsedPrompt prompt)
    {
        var className = prompt.Name + options.ClassSuffix;
        var problems = NameConflicts.Find(prompt, className, FSharpSyntax.PropertyName, "F#");
        if (problems.Count > 0)
        {
            return new EmitResult([], problems);
        }

        var code = new CodeWriter();
        var file = System.IO.Path.GetFileName(prompt.Path);
        var ordered = prompt.Variables.Where(v => v.Required).Concat(prompt.Variables.Where(v => !v.Required)).ToList();

        code.Line("// <auto-generated/>");
        code.Line($"// Generated by TypedPrompt from {file}. Do not edit: change the .prompt.toml file instead.");
        code.Line($"namespace {options.Namespace}");
        code.Line();
        code.Line("open System");
        code.Line("open System.Collections.Generic");
        code.Line("open TypedPrompt");
        code.Line();
        code.Line($"/// <summary>{CSharpSyntax.Xml(prompt.Description ?? $"The prompt defined in {file}.")}</summary>");
        foreach (var variable in ordered)
        {
            code.Line($"/// <param name=\"{FSharpSyntax.PlainParameterName(variable.Name)}\">{CSharpSyntax.Xml(Describe(variable))}</param>");
        }

        code.Line("[<Sealed>]");
        code.Line($"[<System.CodeDom.Compiler.GeneratedCode(\"TypedPrompt\", {FSharpSyntax.Literal(options.GeneratorVersion)})>]");
        code.Line($"type {className}({string.Join(", ", ordered.Select(Parameter))}) =");
        Indent(code, () =>
        {
            WriteBindings(code, ordered);
            WriteDefinition(code, prompt);
            WriteMembers(code, prompt);
        });

        return new EmitResult([new EmittedFile(className + ".g.fs", code.ToString())], []);
    }

    private static void WriteBindings(CodeWriter code, List<ParsedVariable> ordered)
    {
        // No runtime null checks: F# code does not pass null for a string argument, and with nullness checking on the
        // compiler rejects it already. (An isNull check on a non-nullable string would itself be a nullness warning.)
        foreach (var variable in ordered.Where(v => !v.Required && v.Default is not null))
        {
            var name = FSharpSyntax.ParameterName(variable.Name);
            code.Line($"let {name} = defaultArg {name} {FSharpSyntax.Literal(variable.Default!)}");
        }

        code.Line();
    }

    private static void WriteDefinition(CodeWriter code, ParsedPrompt prompt)
    {
        code.Line("static let definition =");
        Indent(code, () =>
        {
            code.Line("PromptDefinition(");
            Indent(code, () =>
            {
                var arguments = new List<string>
                {
                    FSharpSyntax.Literal(prompt.Key),
                    FSharpSyntax.Literal(prompt.User.Text),
                    $"ContentHash = {FSharpSyntax.Literal(prompt.ContentHash)}",
                };

                if (prompt.VersionLabel is { } label)
                {
                    arguments.Add($"VersionLabel = {FSharpSyntax.Literal(label)}");
                }

                if (prompt.System is { } system)
                {
                    arguments.Add($"SystemTemplate = {FSharpSyntax.Literal(system.Text)}");
                }

                if (prompt.Examples.Count > 0)
                {
                    var examples = prompt.Examples.Select(e => $"PromptExample({FSharpSyntax.Literal(e.User.Text)}, {FSharpSyntax.Literal(e.Assistant.Text)})");
                    arguments.Add($"Examples = ({Array(examples)} :> IReadOnlyList<PromptExample>)");
                }

                if (prompt.Description is { } description)
                {
                    arguments.Add($"Description = {FSharpSyntax.Literal(description)}");
                }

                if (prompt.Tags.Count > 0)
                {
                    arguments.Add($"Tags = ({Array(prompt.Tags.Select(FSharpSyntax.Literal))} :> IReadOnlyList<string>)");
                }

                if (prompt.Metadata.Count > 0)
                {
                    var pairs = string.Join("; ", prompt.Metadata.Select(p => $"({FSharpSyntax.Literal(p.Key)}, {FSharpSyntax.Literal(p.Value)})"));
                    arguments.Add($"Metadata = readOnlyDict [ {pairs} ]");
                }

                if (prompt.Model is { } model)
                {
                    arguments.Add($"Model = {Model(model)}");
                }

                if (prompt.OutputSchema is { } schema)
                {
                    arguments.Add($"OutputSchema = {FSharpSyntax.Literal(schema)}");
                }

                if (prompt.Variables.Count > 0)
                {
                    var variables = prompt.Variables.Select(v =>
                        $"VariableInfo({FSharpSyntax.Literal(v.Name)}, VariableType.{v.Kind}, {FSharpSyntax.Literal(v.Required)}, "
                        + $"{FSharpSyntax.Boxed(v.Default)}, {FSharpSyntax.Literal(v.Description)})");
                    arguments.Add($"Variables = ({Array(variables)} :> IReadOnlyList<VariableInfo>)");
                }

                for (var i = 0; i < arguments.Count; i++)
                {
                    code.Line(arguments[i] + (i < arguments.Count - 1 ? "," : ")"));
                }
            });
        });
        code.Line();
    }

    private static string Model(ParsedModelSettings model)
    {
        var arguments = new List<string>();
        if (model.Name is { } name)
        {
            arguments.Add($"Name = {FSharpSyntax.Literal(name)}");
        }

        if (model.Temperature is { } temperature)
        {
            arguments.Add($"Temperature = Nullable {FSharpSyntax.Literal(temperature)}");
        }

        if (model.TopP is { } topP)
        {
            arguments.Add($"TopP = Nullable {FSharpSyntax.Literal(topP)}");
        }

        if (model.TopK is { } topK)
        {
            arguments.Add($"TopK = Nullable {topK.ToString(CultureInfo.InvariantCulture)}");
        }

        if (model.MaxOutputTokens is { } maxTokens)
        {
            arguments.Add($"MaxOutputTokens = Nullable {maxTokens.ToString(CultureInfo.InvariantCulture)}");
        }

        if (model.StopSequences is { } stops)
        {
            arguments.Add($"StopSequences = ({Array(stops.Select(FSharpSyntax.Literal))} :> IReadOnlyList<string>)");
        }

        if (model.Effort is { } effort)
        {
            arguments.Add($"Effort = {FSharpSyntax.Literal(effort)}");
        }

        return $"ModelSettings({string.Join(", ", arguments)})";
    }

    private static void WriteMembers(CodeWriter code, ParsedPrompt prompt)
    {
        code.Line("/// <summary>What the prompt file defines: key, templates, model settings, output schema, variables and metadata.</summary>");
        code.Line("static member Definition = definition");
        code.Line();

        foreach (var variable in prompt.Variables)
        {
            code.Line($"/// <summary>{CSharpSyntax.Xml(Describe(variable))}</summary>");
            code.Line($"member _.{FSharpSyntax.PropertyName(variable.Name)} = {FSharpSyntax.ParameterName(variable.Name)}");
            code.Line();
        }

        code.Line("/// <summary>Fills every placeholder with this instance's values.</summary>");
        code.Line("member _.Render() =");
        Indent(code, () =>
        {
            code.Line("RenderedPrompt(");
            Indent(code, () =>
            {
                code.Line("definition.Key,");
                code.Line($"{(prompt.System is { } system ? Concat(system, prompt) : "null")},");
                code.Line($"{Concat(prompt.User, prompt)},");
                code.Line("definition.Model,");
                code.Line("definition.OutputSchema,");
                if (prompt.Examples.Count == 0)
                {
                    code.Line("Version = definition.Version)");
                }
                else
                {
                    code.Line("Version = definition.Version,");
                    var examples = prompt.Examples.Select(e => $"PromptExample({Concat(e.User, prompt)}, {Concat(e.Assistant, prompt)})");
                    code.Line($"Examples = ({Array(examples)} :> IReadOnlyList<PromptExample>))");
                }
            });
        });
        code.Line();

        code.Line("interface ITypedPrompt with");
        Indent(code, () =>
        {
            code.Line("member _.Definition = definition");
            code.Line("member this.Render() = this.Render()");
        });
    }

    /// <summary>The template pieces as one F# expression: literals and formatted values (options turned into null/Nullable).</summary>
    private static string Concat(Template template, ParsedPrompt prompt)
    {
        var variables = prompt.Variables.ToDictionary(v => v.Name, StringComparer.Ordinal);
        var parts = template.Segments
            .Select(s => s.Kind == TemplateSegmentKind.Text ? FSharpSyntax.Literal(s.Value) : Format(variables[s.Value]))
            .ToList();

        return parts.Count switch
        {
            0 => "\"\"",
            1 => parts[0],
            _ => $"String.Concat({Array(parts)})",
        };
    }

    private static string Format(ParsedVariable variable)
    {
        var name = FSharpSyntax.ParameterName(variable.Name);
        if (variable.Required || variable.Default is not null)
        {
            return $"PromptValue.Format({name})";
        }

        return variable.Kind == VariableKind.Text
            ? $"PromptValue.Format(Option.toObj {name})"
            : $"PromptValue.Format(Option.toNullable {name})";
    }

    private static string Parameter(ParsedVariable variable)
    {
        var type = variable.Kind switch
        {
            VariableKind.Number => "float",
            VariableKind.Boolean => "bool",
            _ => "string",
        };
        var name = FSharpSyntax.ParameterName(variable.Name);
        return variable.Required ? $"{name}: {type}" : $"?{name}: {type}";
    }

    private static string Array(IEnumerable<string> items) => $"[| {string.Join("; ", items)} |]";

    private static string Describe(ParsedVariable variable)
    {
        var text = new StringBuilder(variable.Description ?? $"Value of {{{{{variable.Name}}}}}.");
        if (text.Length > 0 && text[text.Length - 1] is not ('.' or '!' or '?'))
        {
            text.Append('.');
        }

        if (!variable.Required)
        {
            text.Append(variable.Default is null ? " Optional (an option)." : $" Default: {Display(variable.Default)}.");
        }

        return text.ToString();
    }

    private static string Display(object value) => value switch
    {
        double number => number.ToString("R", CultureInfo.InvariantCulture),
        bool flag => flag ? "true" : "false",
        _ => value.ToString() ?? string.Empty,
    };

    private static void Indent(CodeWriter code, Action body)
    {
        code.Push();
        body();
        code.Pop();
    }
}
