namespace TypedPrompt.Core.Tests;

public class CSharpEmitterTests
{
    private static readonly CSharpEmitter Emitter = new(new CSharpEmitOptions("MyApp.Prompts"));

    [Fact]
    public void One_file_per_prompt_named_after_the_class()
    {
        var result = Emit("ticket-summarize.prompt.toml", "user = \"{{ticket}}\"\n[variables.ticket]\ntype = \"text\"\nrequired = true\n");

        var file = Assert.Single(result.Files);
        Assert.Equal("TicketSummarizePrompt.g.cs", file.Name);
        Assert.Contains("namespace MyApp.Prompts", file.Content, StringComparison.Ordinal);
        Assert.Contains("public sealed partial class TicketSummarizePrompt : global::TypedPrompt.ITypedPrompt", file.Content, StringComparison.Ordinal);
        Assert.StartsWith("// <auto-generated/>", file.Content, StringComparison.Ordinal);
    }

    [Fact]
    public void Required_parameters_come_first_and_optional_ones_get_defaults_or_null()
    {
        var content = Content("""
            user = "{{tone}} {{name}} {{count}} {{loud}} {{nick}}"

            [variables.tone]
            type    = "text"
            default = "friendly"

            [variables.name]
            type     = "text"
            required = true

            [variables.count]
            type    = "number"
            default = 2

            [variables.loud]
            type    = "boolean"
            default = true

            [variables.nick]
            type = "text"
            """);

        Assert.Contains(
            "public TestPrompt(string name, string tone = \"friendly\", double count = 2D, bool loud = true, string? nick = null)",
            content,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Variable_names_become_csharp_names_and_keywords_are_escaped()
    {
        var content = Content("user = \"{{max_sentences}} {{class}}\"\n[variables.max_sentences]\ntype = \"number\"\nrequired = true\n[variables.class]\ntype = \"text\"\nrequired = true\n");

        Assert.Contains("double maxSentences, string @class", content, StringComparison.Ordinal);
        Assert.Contains("public double MaxSentences { get; }", content, StringComparison.Ordinal);
        Assert.Contains("Class = @class ?? throw", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Text_is_escaped_into_valid_string_literals()
    {
        var content = Content("user = '''He said \"hi\" \\ back\ttab'''\n");

        Assert.Contains("\"He said \\\"hi\\\" \\\\ back\\ttab\"", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Minimal_prompt_has_no_optional_definition_members()
    {
        var content = Content("user = \"Hello\"\n");

        Assert.DoesNotContain("SystemTemplate", content, StringComparison.Ordinal);
        Assert.DoesNotContain("Model =", content, StringComparison.Ordinal);
        Assert.DoesNotContain("Variables =", content, StringComparison.Ordinal);
        Assert.Contains("public TestPrompt()", content, StringComparison.Ordinal);
        Assert.Contains("                null,\n                \"Hello\",", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Model_settings_are_written_only_when_set()
    {
        var withEffort = Content("user = \"Hi\"\n[model]\nname = \"m\"\neffort = \"high\"\n");
        var withoutEffort = Content("user = \"Hi\"\n[model]\nname = \"m\"\n");

        Assert.Contains("Model = new global::TypedPrompt.ModelSettings(Name: \"m\", Effort: \"high\"),", withEffort, StringComparison.Ordinal);
        Assert.Contains("Model = new global::TypedPrompt.ModelSettings(Name: \"m\"),", withoutEffort, StringComparison.Ordinal);
    }

    [Fact]
    public void Examples_are_in_the_definition_and_rendered_with_their_placeholders()
    {
        var content = Content("user = \"{{q}}\"\n\n[[examples]]\nuser = \"Hi {{q}}\"\nassistant = \"Hello\"\n\n[variables.q]\ntype = \"text\"\nrequired = true\n");

        Assert.Contains("new global::TypedPrompt.PromptExample(\"Hi {{q}}\", \"Hello\"),", content, StringComparison.Ordinal);
        Assert.Contains(
            "new global::TypedPrompt.PromptExample(string.Concat(new string[] { \"Hi \", global::TypedPrompt.PromptValue.Format(Q) }), \"Hello\"),",
            content,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Render_concatenates_literals_and_formatted_values()
    {
        var content = Content("user = \"Hi {{name}}!\"\n[variables.name]\ntype = \"text\"\nrequired = true\n");

        Assert.Contains("string.Concat(new string[] { \"Hi \", global::TypedPrompt.PromptValue.Format(Name), \"!\" })", content, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("[variables.max_tokens]\ntype = \"text\"\n[variables.maxTokens]\ntype = \"text\"\n", "{{max_tokens}}{{maxTokens}}", "both become the C# property 'MaxTokens'")]
    [InlineData("[variables.render]\ntype = \"text\"\n", "{{render}}", "'Render', which the generated class already uses")]
    [InlineData("[variables.test_prompt]\ntype = \"text\"\n", "{{test_prompt}}", "'TestPrompt', which the generated class already uses")]
    public void TP013_names_that_clash_in_csharp(string variables, string user, string expected)
    {
        var result = Emit("test.prompt.toml", $"user = \"{user}\"\n{variables}");

        Assert.Empty(result.Files);
        var problem = Assert.Single(result.Problems);
        Assert.Equal("TP013", problem.Id);
        Assert.Contains(expected, problem.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parameter_docs_carry_the_description_and_the_default()
    {
        var content = Content("user = \"{{tone}}\"\n[variables.tone]\ntype = \"text\"\ndefault = \"friendly\"\ndescription = \"e.g. friendly or formal\"\n");

        Assert.Contains("/// <param name=\"tone\">e.g. friendly or formal. Default: friendly.</param>", content, StringComparison.Ordinal);
    }

    private static string Content(string toml) => Assert.Single(Emit("test.prompt.toml", toml).Files).Content;

    private static EmitResult Emit(string file, string toml)
    {
        var parsed = PromptFileParser.Parse("prompts/" + file, toml);
        Assert.True(parsed.Prompt is not null, string.Join("\n", parsed.Problems));
        return Emitter.Emit(parsed.Prompt);
    }
}
