<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TypedPrompt\TypedPrompt.csproj" />
    <ProjectReference Include="..\..\src\TypedPrompt.CSharp.Generator\TypedPrompt.CSharp.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Prompts\**\*.prompt.toml" />
    <CompilerVisibleProperty Include="RootNamespace" />
    <CompilerVisibleProperty Include="TypedPromptNamespace" />
  </ItemGroup>

</Project>
